;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Anthill",NewTagName="Unit.Type.Anthill")
+GameplayTagRedirects=(OldTagName="Wasp",NewTagName="Unit.Type.Wasp")
+GameplayTagRedirects=(OldTagName="Truck",NewTagName="Unit.Type.Truck")
+GameplayTagRedirects=(OldTagName="Harvester",NewTagName="Unit.Type.Harvester")
+GameplayTagRedirects=(OldTagName="BulletAnt",NewTagName="Unit.Type.BulletAnt")
+GameplayTagList=(Tag="Grid.Size.Standard",DevComment="")
+GameplayTagList=(Tag="Grid.Type.DoubleCost",DevComment="")
+GameplayTagList=(Tag="Grid.Type.FlyingUnitsOnly",DevComment="")
+GameplayTagList=(Tag="Grid.Type.Normal",DevComment="")
+GameplayTagList=(Tag="Grid.Type.Obstacle",DevComment="")
+GameplayTagList=(Tag="Grid.Type.TripleCost",DevComment="")
+GameplayTagList=(Tag="Grid.Visual.Black",DevComment="")
+GameplayTagList=(Tag="Grid.Visual.Blue",DevComment="")
+GameplayTagList=(Tag="Grid.Visual.Green",DevComment="")
+GameplayTagList=(Tag="Grid.Visual.Red",DevComment="")
+GameplayTagList=(Tag="Unit.Type.Anthill",DevComment="")
+GameplayTagList=(Tag="Unit.Type.BulletAnt",DevComment="")
+GameplayTagList=(Tag="Unit.Type.Harvester",DevComment="")
+GameplayTagList=(Tag="Unit.Type.Truck",DevComment="")
+GameplayTagList=(Tag="Unit.Type.Wasp",DevComment="")

