;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Anthill",NewTagName="Unit.Type.Anthill")
+GameplayTagRedirects=(OldTagName="Wasp",NewTagName="Unit.Type.Wasp")
+GameplayTagRedirects=(OldTagName="Truck",NewTagName="Unit.Type.Truck")
+GameplayTagRedirects=(OldTagName="Harvester",NewTagName="Unit.Type.Harvester")
+GameplayTagRedirects=(OldTagName="BulletAnt",NewTagName="Unit.Type.BulletAnt")
+GameplayTagRedirects=(OldTagName="Grid.Type.TripleCost",NewTagName="Grid.Type.Blocked")
+GameplayTagRedirects=(OldTagName="Grid.Type.Normal",NewTagName="Grid.Type.Walkable")
+GameplayTagRedirects=(OldTagName="Unit.Role.Ranger",NewTagName="Unit.Role.Range")
+GameplayTagRedirects=(OldTagName="Unit.Role.Range",NewTagName="Unit.Role.Ranged")
+GameplayTagList=(Tag="Grid.Cost.Double",DevComment="")
+GameplayTagList=(Tag="Grid.Cost.Simple",DevComment="")
+GameplayTagList=(Tag="Grid.Cost.Triple",DevComment="")
+GameplayTagList=(Tag="Grid.Size.Standard",DevComment="")
+GameplayTagList=(Tag="Grid.Type.Blocked",DevComment="")
+GameplayTagList=(Tag="Grid.Type.FlyingOnly",DevComment="")
+GameplayTagList=(Tag="Grid.Type.Obstacle",DevComment="")
+GameplayTagList=(Tag="Grid.Type.Walkable",DevComment="")
+GameplayTagList=(Tag="Grid.Visual.Black",DevComment="")
+GameplayTagList=(Tag="Grid.Visual.Blue",DevComment="")
+GameplayTagList=(Tag="Grid.Visual.Green",DevComment="")
+GameplayTagList=(Tag="Grid.Visual.Red",DevComment="")
+GameplayTagList=(Tag="Unit.AI.LastMovement.AwayFromAllies",DevComment="")
+GameplayTagList=(Tag="Unit.AI.LastMovement.AwayFromEnemies",DevComment="")
+GameplayTagList=(Tag="Unit.AI.LastMovement.TowardsClosestAlly",DevComment="")
+GameplayTagList=(Tag="Unit.AI.LastMovement.TowardsClosestEnemy",DevComment="")
+GameplayTagList=(Tag="Unit.Faction.Machine",DevComment="")
+GameplayTagList=(Tag="Unit.Faction.Nature",DevComment="")
+GameplayTagList=(Tag="Unit.Movement.Flying",DevComment="")
+GameplayTagList=(Tag="Unit.Movement.Ground",DevComment="")
+GameplayTagList=(Tag="Unit.Role.Blocker",DevComment="")
+GameplayTagList=(Tag="Unit.Role.Charger",DevComment="")
+GameplayTagList=(Tag="Unit.Role.DamageDealer",DevComment="")
+GameplayTagList=(Tag="Unit.Role.Meelee",DevComment="")
+GameplayTagList=(Tag="Unit.Role.Ranged",DevComment="")
+GameplayTagList=(Tag="Unit.Type.Anthill",DevComment="")
+GameplayTagList=(Tag="Unit.Type.BulletAnt",DevComment="")
+GameplayTagList=(Tag="Unit.Type.Harvester",DevComment="")
+GameplayTagList=(Tag="Unit.Type.Truck",DevComment="")
+GameplayTagList=(Tag="Unit.Type.Wasp",DevComment="")

